### ISSUE TITLE
Ошибка при запуске bundle install

### ISSUE THREAD

**Issue by AlekseySemiconductor** [shikimori/shikimori#2545]
Ubuntu 22.04, nodejs 16.17.0, ruby 2.6.10;

Устанавливаю проект, запуская `bundle install`, но в консоль выводится следующее:

```
shikimori/_vendor/ruby/2.6.0/gems/http_parser.rb-0.6.0/ext/ruby_http_parser:
linker input file unused because linking not done
gcc: error:
shikimori/_vendor/ruby/2.6.0/gems/http_parser.rb-0.6.0/ext/ruby_http_parser:
linker input file not found: Нет такого файла или каталога
make: *** [Makefile:245: ruby_http_parser.o] Ошибка 1

make failed, exit code 2
```

```
An error occurred while installing http_parser.rb (0.6.0), and Bundler
cannot continue.

In Gemfile:
  faye was resolved to 1.4.0, which depends on
    em-http-request was resolved to 1.1.7, which depends on
      http_parser.rb
```

Кто-нибудь сталкивался с такой проблемой? Как её можно было бы решить?

**Comment by morr** [comment]
@AlekseySemiconductor `http_parser.rb` не может скомпилироваться. нужно попробовать установить его отдельно `gem install http_parser.rb` и посмотреть, что за ошибку выдаст. возможно там будет файл с логом, где будут детальнее описана ошибка

должно отработать примерно вот так
![image](https://user-images.githubusercontent.com/134610/187023931-c56f59dd-bbe4-4957-ad88-c7559f65a593.png)

возможно не хватает какой-то системной библиотеки для компиляции?

на продакшен сервере шикимори тоже убунта, туда устанавливаются следующие доп библиотеки
```
  'libgmp-dev'
  'libxrender1',
  'libfontconfig1',
  'libxtst6',
  'libpq-dev',
  'libjpeg-progs'
```
зачем каждая из них нужна, я уже не помню. без каждой из списка что-то когда-то не работало, но, возможно, всё из перечисленного уже не актуально, и устанавливать их не требуется

**Comment by AlekseySemiconductor** [comment]
установил http_parser.rb, всё устновилось без ошибок:
```
gem install http_parser.rb
Building native extensions. This could take a while...
Successfully installed http_parser.rb-0.8.0
Parsing documentation for http_parser.rb-0.8.0
unknown encoding name "chunked\r\n\r\n25" for ext/ruby_http_parser/vendor/http-parser-java/tools/parse_tests.rb, skipping
Done installing documentation for http_parser.rb after 0 seconds
1 gem installed
```
затем установил 6 библиотек для убунту (тоже всё установилось без ошибок), но запуск bundle install по-прежнему выдаёт ошибку: An error occurred while installing http_parser.rb (0.6.0), and Bundler cannot continue.
Пытался установить версию http_parser.rb 0.6.0, запустив `gem install http_parser.rb -v 0.6.0`, но, к сожалению, не помогло.

Вот, что выводит после установки http_parser.rb и запуска bundle install:
```
bundle install
Fetching gem metadata from https://rubygems.org/.........
Using rake 13.0.6
Using concurrent-ruby 1.1.10
Using minitest 5.16.0
Using zeitwerk 2.6.0
Using builder 3.2.4
Using erubi 1.10.0
Using racc 1.6.0
Using active_record_query_trace 1.6.2
Using acts_as_votable 0.13.1
Using public_suffix 4.0.6
Using net-ssh 6.1.0
Using sexp_processor 4.16.1
Using sync 0.5.0
Using crass 1.0.6
Using ast 2.4.2
Using nio4r 2.5.8
Using websocket-extensions 0.1.5
Using mini_mime 1.1.2
Using bcrypt 3.1.16
Using rack 2.2.3.1
Using msgpack 1.5.1
Using coderay 1.1.3
Using brakeman 5.2.2
Using browser 5.3.1
Using redis 4.6.0
Using bundler 2.3.21
Using debug_inspector 1.1.0
Using cancancan 3.0.1 from https://github.com/morr/cancancan.git (at master@0f536f8)
Using marcel 1.0.2
Using regexp_parser 2.5.0
Using jsonapi-renderer 0.2.2
Using matrix 0.4.2
Using attr_extras 6.2.5
Using faraday-excon 1.1.0
Using faraday-em_synchrony 1.0.0
Using faraday-net_http 1.0.1
Using faraday-net_http_persistent 1.2.0
Using faraday-patron 1.0.0
Using faraday-rack 1.0.0
Using multipart-post 2.1.1
Using ruby2_keywords 0.0.5
Using execjs 2.7.0
Using climate_control 0.2.0
Using colorize 0.8.1
Using connection_pool 2.2.5
Using cookiejar 0.3.3
Using rexml 3.2.5
Using byebug 11.1.3
Using faraday-httpclient 1.0.1
Using dalli 2.7.11
Using orm_adapter 0.5.0
Using method_source 1.0.0
Using thor 1.2.1
Using diff-lcs 1.5.0
Using unf_ext 0.0.8.1
Using amazing_print 1.4.0
Using draper-cancancan 1.1.1
Using dry-inflector 0.2.0
Using eventmachine 1.2.7
Using multi_json 1.15.0
Using ffi 1.15.5
Using formatador 0.3.0
Using rspec-support 3.11.0
Using dotenv 2.7.6
Using mime-types-data 3.2022.0105
Using multi_xml 0.6.0
Using json 2.5.1
Using google-protobuf 3.20.0 (x86_64-linux)
Using faraday-em_http 1.0.0
Using elasticsearch-dsl 0.1.9
Using lumberjack 1.2.8
Using shellany 0.0.1
Using guard-compat 1.2.1
Using parallel 1.22.1
Using rainbow 3.1.1
Using database_cleaner-core 2.0.1
Using nenv 0.3.0
Using hashdiff 1.0.1
Using hashie 4.1.0
Using htmlentities 4.3.4
Using ice_cube 0.16.3
Using jwt 2.2.3
Using spring 2.1.1
Using ruby-progressbar 1.11.0
Using mactag 0.7.2
Using maruku 0.7.3
Using mini_magick 4.11.0
Using oauth 0.5.6
Using open_uri_redirections 0.2.1
Using paperclip-i18n 4.3.0
Using pg 1.3.5
Using raindrops 0.20.0
Using retryable 3.0.5
Using unicode 0.4.4.4
Using rb-fsevent 0.11.1
Using daemons 1.4.0
Using shallow_attributes 0.9.5 from https://github.com/morr/shallow_attributes.git (at master@cef697d)
Using unicode-display_width 2.1.0
Using sixarm_ruby_unaccent 1.2.0
Using kgio 2.11.4
Using tilt 2.0.10
Using stackprof 0.2.19
Using timecop 0.9.5
Using translit 0.1.5
Using truncate_html 0.9.3
Using turbolinks-source 5.2.0
Using vcr 6.1.0
Using xxhash 0.4.0
Using semantic_range 3.0.0
Using tzinfo 2.0.4
Using bugsnag 6.24.2
Using concurrent-ruby-edge 0.6.0
Using dry-core 0.5.0
Using i18n 1.8.11
Using websocket-driver 0.7.5
Using mail 2.7.1
Using addressable 2.8.0
Using net-scp 3.0.0
Using ruby_parser 3.19.1
Using tins 1.26.0
Using temple 0.8.2
Using rack-test 1.1.0
Using aasm 5.2.0
Using brpoplpush-redis_script 0.1.2
Using warden 1.2.9
Using sprockets 4.0.3
Using nokogiri 1.13.6 (x86_64-linux)
Using better_errors 2.9.1
Using request_store 1.5.1
Using rack-attack 6.6.0
Using rack-cors 1.1.1
Using ruby-esvidi 0.5.3 from https://github.com/shikimori/ruby-esvidi.git (at master@7171659)
Using rack-proxy 0.7.2
Using rack-utf8_sanitizer 1.7.0
Using redis-namespace 1.8.2
Using binding_of_caller 1.0.0
Using bootsnap 1.11.1
Using autoprefixer-rails 10.4.2.0
Using rack-protection 2.2.0
Using puma 5.6.4
Using sidekiq 6.5.0
Using parser 3.1.2.0
Using unf 0.1.4
Using pry 0.13.1
Using terrapin 0.6.0
Using elasticsearch-api 7.6.0
Using em-socksify 0.3.2
Using rspec-core 3.11.0
Using crack 0.4.5
Using rspec-mocks 3.11.1
Using rb-inotify 0.10.1
Using recaptcha 5.8.1
Using sassc 2.4.0
Using faraday 1.8.0
Using parallel_tests 3.7.3
Using notiffany 0.1.3
Using uglifier 4.2.0
Using spring-commands-rspec 1.0.4
Using thin 1.8.1
Using turbolinks 5.2.1
Using unicorn 6.1.0
Using activesupport 6.1.5
Using sshkit 1.21.2
Using rb-fchange 0.0.6
Using htmldiff-lcs 0.0.1 from https://github.com/nbudin/htmldiff-lcs.git (at master@efeec72)
Using dry-logic 1.2.0
Using faye-websocket 0.11.0
Using i18n-js 3.9.0
Using i18n-inflector 2.6.7 from https://github.com/morr/i18n-inflector.git (at master@fc09423)
Using protocol 2.0.0
Using slim 4.1.0
Using loofah 2.18.0
Using xpath 3.2.0
Using dry-configurable 0.12.1
Using mimemagic 0.3.10
Using non-stupid-digest-assets 1.0.9
Using redis-classy 2.4.1
Using omniauth 2.0.4
Using rspec-expectations 3.11.0
Using domain_name 0.5.20190701
Using mal_parser 0.2.0 from https://github.com/shikimori/mal_parser.git (at master@eb324d6)
Using mime-types 3.4.1
Using sidekiq-delay_extensions 6.4.1
Using sidekiq-limit_fetch 4.2.0
Using sidekiq-unique-jobs 7.1.25
Using fuubar 2.5.1
Using rspec_junit_formatter 0.5.1
Using webmock 3.14.0
Using elasticsearch-transport 7.6.0
Using icalendar 2.7.1
Using listen 3.7.1
Using oauth2 1.4.7
Using rails-dom-testing 2.0.3
Using globalid 1.0.0
Using pry-rails 0.3.9
Using rubocop-ast 1.18.0
Using clockwork 2.0.4
Using enumerize 2.4.0
Using factory_bot 6.2.0
Using case_transform 0.2
Using rs_russian 0.20.0 from https://github.com/morr/rs_russian.git (at master@cce1516)
Using shoulda-matchers 5.1.0
Using pry-byebug 3.9.0
Using rails-html-sanitizer 1.4.3
Using mize 0.3.5
Using capybara 3.36.0
Using dry-container 0.7.2
Using redis-mutex 4.0.2
Using rspec 3.11.0
Using airbrussh 1.4.0
Using rspec-collection_matchers 1.2.0
Using rspec-its 1.3.0
Using http-cookie 1.0.3
Using activejob 6.1.5
Using elasticsearch 7.6.0
Using httparty 0.18.1
Using activemodel 6.1.5
Using omniauth-oauth2 1.7.1
Using jbuilder 2.11.2
Using factory_girl-seeds 1.1.0 from https://github.com/morr/factory_girl-seeds.git (at use-factory-bot@36235fe)
Using omniauth-oauth 1.2.0
Using guard 2.18.0
Using actionview 6.1.5
Using launchy 2.5.0
Using chewy 6.0.0
Using dry-types 1.5.1
Using faraday-cookie_jar 0.0.7
Using capistrano 3.17.0
Using activerecord 6.1.5
Using amatch 0.4.0 from https://github.com/flori/amatch.git (at master@351285f)
Using spring-watcher-listen 2.0.1
Using paperclip 6.1.0
Using omniauth-facebook 8.0.0
Using omniauth-vkontakte 1.7.0
Using guard-brakeman 0.8.6
Using faraday_middleware 1.2.0
Using rubocop 1.30.1
Using guard-pow 2.0.0
Using guard-rspec 4.7.3
Using guard-spring 1.1.1
Using omniauth-twitter 1.4.0
Using actionpack 6.1.5
Using letter_opener 1.7.0
Using gcm 0.1.1
Using activemodel-serializers-xml 1.0.2
Using capistrano-rbenv 2.2.0
Using activerecord-import 1.4.0
Using acts_as_list 1.0.3
Using database_cleaner-active_record 2.0.1
Using pghero 2.8.2
Using actioncable 6.1.5
Using guard-bundler 3.0.0
Using actionmailer 6.1.5
Using capistrano-bundler 2.0.1
Using activestorage 6.1.5
Using apipie-rails 0.7.1
Using railties 6.1.5
Using sprockets-rails 3.4.2
Using gon 6.4.0
Using omniauth-rails_csrf_protection 1.0.0
Using rails-controller-testing 1.0.5
Using rubocop-performance 1.14.2
Using rubocop-rails 2.15.0
Using simple_form 5.1.0
Using database_cleaner 2.0.1
Using draper 4.0.2
Using guard-rubocop 1.5.0
Using actionmailbox 6.1.5
Using actiontext 6.1.5
Using responders 3.0.1
Using guard-i18n-js 1.0.0 from https://github.com/morr/guard-i18n-js.git (at master@9e7210e)
Using dotenv-rails 2.7.6
Using factory_bot_rails 6.2.0
Using lograge 0.12.0
Using rails-i18n 7.0.3
Using actionpack-action_caching 1.2.2
Using active_model_serializers 0.10.13
Using slim-rails 3.4.0
Using webpacker 5.4.3
Using devise 4.8.0
Using rails 6.1.5
Using simple_form-magic_submit 1.2.0 from https://github.com/morr/simple_form-magic_submit.git (at master@89cfeaa)
Using capistrano-rails 1.6.2
Using doorkeeper 5.2.1
Using capistrano-copy-files 0.0.1
Using rspec-rails 5.1.2
Using devise-doorkeeper 1.1.2 from https://github.com/morr/devise-doorkeeper.git (at master@fc0245f)
Using sassc-rails 2.1.2
Installing http_parser.rb 0.6.0 with native extensions
Installing pg_query 2.1.3 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /home/aleksey/Рабочий стол/github-projects/AlekseySemiconductor/shiki/shikimori/_vendor/ruby/2.6.0/gems/http_parser.rb-0.6.0/ext/ruby_http_parser
/home/aleksey/.asdf/installs/ruby/2.6.10/bin/ruby -I /home/aleksey/.asdf/installs/ruby/2.6.10/lib/ruby/2.6.0 -r ./siteconf20220827-55305-rjdx4q.rb extconf.rb
creating Makefile

current directory: /home/aleksey/Рабочий стол/github-projects/AlekseySemiconductor/shiki/shikimori/_vendor/ruby/2.6.0/gems/http_parser.rb-0.6.0/ext/ruby_http_parser
make "DESTDIR=" clean

current directory: /home/aleksey/Рабочий стол/github-projects/AlekseySemiconductor/shiki/shikimori/_vendor/ruby/2.6.0/gems/http_parser.rb-0.6.0/ext/ruby_http_parser
make "DESTDIR="
compiling ruby_http_parser.c
ruby_http_parser.c: In function ‘on_message_begin’:
ruby_http_parser.c:108:3: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
  108 |   VALUE ret = Qnil;
      |   ^~~~~
ruby_http_parser.c: In function ‘on_header_value’:
ruby_http_parser.c:146:3: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
  146 |   int new_field = 0;
      |   ^~~
ruby_http_parser.c: In function ‘on_headers_complete’:
ruby_http_parser.c:192:3: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
  192 |   VALUE ret = Qnil;
      |   ^~~~~
ruby_http_parser.c: In function ‘on_body’:
ruby_http_parser.c:213:3: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
  213 |   VALUE ret = Qnil;
      |   ^~~~~
ruby_http_parser.c: In function ‘on_message_complete’:
ruby_http_parser.c:232:3: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
  232 |   VALUE ret = Qnil;
      |   ^~~~~
ruby_http_parser.c: In function ‘Parser_execute’:
ruby_http_parser.c:314:3: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
  314 |   char *ptr = RSTRING_PTR(data);
      |   ^~~~
ruby_http_parser.c:320:3: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
  320 |   size_t nparsed = ryah_http_parser_execute(&wrapper->parser, &settings, ptr, len);
      |   ^~~~~~
ruby_http_parser.c: In function ‘Parser_set_header_value_type’:
ruby_http_parser.c:451:3: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
  451 |   ParserWrapper *wrapper = NULL;
      |   ^~~~~~~~~~~~~
ruby_http_parser.c: At top level:
cc1: note: unrecognized command-line option ‘-Wno-self-assign’ may have been intended to silence earlier diagnostics
cc1: note: unrecognized command-line option ‘-Wno-parentheses-equality’ may have been intended to silence earlier diagnostics
cc1: note: unrecognized command-line option ‘-Wno-constant-logical-operand’ may have been intended to silence earlier diagnostics
gcc: warning: стол/github-projects/AlekseySemiconductor/shiki/shikimori/_vendor/ruby/2.6.0/gems/http_parser.rb-0.6.0/ext/ruby_http_parser: linker input file unused because linking not done
gcc: error: стол/github-projects/AlekseySemiconductor/shiki/shikimori/_vendor/ruby/2.6.0/gems/http_parser.rb-0.6.0/ext/ruby_http_parser: linker input file not found: Нет такого файла или каталога
make: *** [Makefile:245: ruby_http_parser.o] Ошибка 1

make failed, exit code 2

Gem files will remain installed in /home/aleksey/Рабочий стол/github-projects/AlekseySemiconductor/shiki/shikimori/_vendor/ruby/2.6.0/gems/http_parser.rb-0.6.0 for inspection.
Results logged to /home/aleksey/Рабочий стол/github-projects/AlekseySemiconductor/shiki/shikimori/_vendor/ruby/2.6.0/extensions/x86_64-linux/2.6.0/http_parser.rb-0.6.0/gem_make.out

  /home/aleksey/.asdf/installs/ruby/2.6.10/lib/ruby/2.6.0/rubygems/ext/builder.rb:99:in `run'
  /home/aleksey/.asdf/installs/ruby/2.6.10/lib/ruby/2.6.0/rubygems/ext/builder.rb:51:in `block in make'
  /home/aleksey/.asdf/installs/ruby/2.6.10/lib/ruby/2.6.0/rubygems/ext/builder.rb:43:in `each'
  /home/aleksey/.asdf/installs/ruby/2.6.10/lib/ruby/2.6.0/rubygems/ext/builder.rb:43:in `make'
  /home/aleksey/.asdf/installs/ruby/2.6.10/lib/ruby/2.6.0/rubygems/ext/ext_conf_builder.rb:62:in `block in build'
  /home/aleksey/.asdf/installs/ruby/2.6.10/lib/ruby/2.6.0/tempfile.rb:295:in `open'
  /home/aleksey/.asdf/installs/ruby/2.6.10/lib/ruby/2.6.0/rubygems/ext/ext_conf_builder.rb:29:in `build'
  /home/aleksey/.asdf/installs/ruby/2.6.10/lib/ruby/2.6.0/rubygems/ext/builder.rb:185:in `block in build_extension'
  /home/aleksey/.asdf/installs/ruby/2.6.10/lib/ruby/2.6.0/monitor.rb:235:in `mon_synchronize'
  /home/aleksey/.asdf/installs/ruby/2.6.10/lib/ruby/2.6.0/rubygems/ext/builder.rb:181:in `build_extension'
  /home/aleksey/.asdf/installs/ruby/2.6.10/lib/ruby/2.6.0/rubygems/ext/builder.rb:229:in `block in build_extensions'
  /home/aleksey/.asdf/installs/ruby/2.6.10/lib/ruby/2.6.0/rubygems/ext/builder.rb:226:in `each'
  /home/aleksey/.asdf/installs/ruby/2.6.10/lib/ruby/2.6.0/rubygems/ext/builder.rb:226:in `build_extensions'
  /home/aleksey/.asdf/installs/ruby/2.6.10/lib/ruby/2.6.0/rubygems/installer.rb:830:in `build_extensions'
  /home/aleksey/.asdf/installs/ruby/2.6.10/lib/ruby/gems/2.6.0/gems/bundler-2.3.21/lib/bundler/rubygems_gem_installer.rb:72:in `build_extensions'
  /home/aleksey/.asdf/installs/ruby/2.6.10/lib/ruby/gems/2.6.0/gems/bundler-2.3.21/lib/bundler/rubygems_gem_installer.rb:28:in `install'
  /home/aleksey/.asdf/installs/ruby/2.6.10/lib/ruby/gems/2.6.0/gems/bundler-2.3.21/lib/bundler/source/rubygems.rb:207:in `install'
  /home/aleksey/.asdf/installs/ruby/2.6.10/lib/ruby/gems/2.6.0/gems/bundler-2.3.21/lib/bundler/installer/gem_installer.rb:54:in `install'
  /home/aleksey/.asdf/installs/ruby/2.6.10/lib/ruby/gems/2.6.0/gems/bundler-2.3.21/lib/bundler/installer/gem_installer.rb:16:in `install_from_spec'
  /home/aleksey/.asdf/installs/ruby/2.6.10/lib/ruby/gems/2.6.0/gems/bundler-2.3.21/lib/bundler/installer/parallel_installer.rb:186:in `do_install'
  /home/aleksey/.asdf/installs/ruby/2.6.10/lib/ruby/gems/2.6.0/gems/bundler-2.3.21/lib/bundler/installer/parallel_installer.rb:177:in `block in worker_pool'
  /home/aleksey/.asdf/installs/ruby/2.6.10/lib/ruby/gems/2.6.0/gems/bundler-2.3.21/lib/bundler/worker.rb:62:in `apply_func'
  /home/aleksey/.asdf/installs/ruby/2.6.10/lib/ruby/gems/2.6.0/gems/bundler-2.3.21/lib/bundler/worker.rb:57:in `block in process_queue'
  /home/aleksey/.asdf/installs/ruby/2.6.10/lib/ruby/gems/2.6.0/gems/bundler-2.3.21/lib/bundler/worker.rb:54:in `loop'
  /home/aleksey/.asdf/installs/ruby/2.6.10/lib/ruby/gems/2.6.0/gems/bundler-2.3.21/lib/bundler/worker.rb:54:in `process_queue'
  /home/aleksey/.asdf/installs/ruby/2.6.10/lib/ruby/gems/2.6.0/gems/bundler-2.3.21/lib/bundler/worker.rb:91:in `block (2 levels) in create_threads'

An error occurred while installing http_parser.rb (0.6.0), and Bundler cannot continue.

In Gemfile:
  faye was resolved to 1.4.0, which depends on
    em-http-request was resolved to 1.1.7, which depends on
      http_parser.rb
```

**Comment by morr** [comment]
@AlekseySemiconductor предположения в порядке бреда

при использовании rbenv `gem install http_parser.rb -v 0.6.0` ставится в тот же каталог, куда будет установлен гем командой `bundle install`. то есть после успешного `gem install` при выполнении `bundle` команды, гем повторно ставиться не должен.
так работает установка гемов при использовании `rbenv`.
asdf, как мы видим, ставит в локальный каталог и падает, а при установке не в локальный каталог через gem install не падает
вывод: какая-то проблема с asdf. возможно, дело в русских символах в пути (что-то не работает с юникодом? но это маловероятно)
![image](https://user-images.githubusercontent.com/134610/187072459-a5ea787c-1a8e-4b93-9945-7a285c6d5b85.png)

попробуй 1. ставить куда-то, где в пути нет русских букв
если не поможет, то 2. замени `asdf` на `rbenv `

**Comment by AlekseySemiconductor** [comment]
Да, здорово, перенёс в каталог, где нету русских букв и всё установилось.
Спасибо, закрываю issue)
